apiVersion: v1
kind: Pod
metadata:
  name: makelogs
spec:
  containers:
  - image: docker.io/glennswest/makelogs:b16e813
    name: makelogs
  volumes:
    - name: secret-volume
      secret:
        secretName: makelogs-secret
