apiVersion: v1
kind: Pod
metadata:
  name: makelogs
spec:
  containers:
  - image: docker.io/glennswest/makelogs:8ad50b3
    name: makelogs
    volumeMounts:
       - name: secret-volume
         mountPath: /etc/secret-volume
         readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: makelogs-secret
